### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [traffordDataLab/tools#1]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by itsozz** [comment]
Hi TJ, whilst I appreciate your efforts to collaborate and support open source projects I feel your method may not achieve the desired result.  By raising an issue on GitHub you are implying that something is wrong and requires fixing, rather than what you intended which was to offer your services. You might perhaps be better sending an email in this instance?  I hope this helps and I wish you all best, however we are perfectly happy with our current logo as it stands.

**Comment by tjulises** [comment]
Thanks for the advice, I apologyze for opening an issue, cheers!
